version: "2"

linters:
  default: none
  enable:
    - govet
    - ineffassign
    - misspell
    - staticcheck
    - unused

  settings:
    staticcheck:
      checks:
        - all
        - -ST1000
        - -ST1003
        - -ST1020
        - -ST1021
        - -ST1022

  exclusions:
    generated: lax
    presets:
      - comments
      - std-error-handling
    paths:
      - docs

formatters:
  enable:
    - gofmt

issues:
  max-issues-per-linter: 0
  max-same-issues: 0
